Repository wanted-running-sheep/sheep-play, pull requests merged in 2022-07, with the labels that each got.

#5 ✨ feat: data fetch 모듈 + json server 세팅
  package-lock.json
  package.json
  src/database/database.json
  src/http/httpRequest.ts
  src/models/useMovieModel.ts
  src/services/movieService.ts
Labels: ⚙️ 설정, ❕중요

#11 💩 chore: #10 영화 데이터 변경
  src/@types/api.d.ts
  src/database/database.json
  src/http/httpRequest.ts
  src/models/useMovieModel.ts
Labels: ⬆️ 리팩토링

#12 ✨ feat: 모달 컴포넌트 레이아웃 추가
  src/components/Modal.tsx
Labels: 📱 UI, 🕹️ 기능

#13 ✨ feat: 네비게이션바 추가
  src/App.tsx
  src/assets/icons/Menu.tsx
  src/components/navBar/DropDownMenu.tsx
  src/components/navBar/Item.tsx
  src/components/navBar/MenuItem.tsx
  src/components/navBar/index.tsx
  src/pages/SearchPage.tsx
Labels: 📱 UI, 🕹️ 기능

#14 ✨ feat: 검색 컴포넌트 (검색창, 검색결과 디자인만)
  src/components/MovieSearch/SearchInput.tsx
  src/components/MovieSearch/SearchedList.tsx
  src/components/MovieSearch/index.tsx
Labels: 📱 UI

#15 ✨ feat: lottie animation 컴포넌트 추가
  src/assets/animation/rocket.json
  src/components/Animation.tsx
Labels: 📱 UI

#21 🐛 fix: data fetching 모듈 promise 버그 수정
  src/modules/http/httpRequest.ts
  src/modules/models/useMovieModel.ts
Labels: 🐞 버그

#24 ✨ feat: Modal 컴포넌트 추가
  src/App.tsx
  src/assets/icons/Add.tsx
  src/assets/icons/Close.tsx
  src/assets/icons/Star.tsx
  src/assets/icons/index.ts
  src/components/Modal/MovieInfo.tsx
  src/components/Modal/index.tsx
  src/styles/mixins.ts
  src/styles/theme.ts
Labels: 📱 UI, 🕹️ 기능

#30 ✨ feat: 반응형 퍼블리싱 및 모달 데이터 동적으로 가져오도록 기능 추가
  src/assets/icons/Add.tsx
  src/components/Modal/MovieInfo.tsx
  src/components/Modal/index.tsx
  src/components/Slide/index.tsx
  src/modules/http/httpRequest.ts
  src/modules/models/useMovieModel.ts
  src/styles/theme.ts
Labels: 📱 UI, 🕹️ 기능

#33 ✨ feat: 영화 총 시간 포맷 변경 및 디자인 수정
  src/components/Modal/MovieInfo.tsx
  src/components/Modal/index.tsx
  src/utils/timeConvert.ts
Labels: 📱 UI

#40 ✨ feat: 데이터 없을 시 보이는 컴포넌트 path에 따라 다르게 보이도록 수정
  src/components/Bookmark/NoData.tsx
  src/pages/BookmarkPage.tsx
Labels: 📱 UI

#42 💄 style: fonts 변경
  package-lock.json
  public/index.html
  src/components/Modal/MovieInfo.tsx
  src/components/MovieSearch/index.tsx
  src/components/navBar/index.tsx
  src/styles/globalStyles.ts
Labels: 📱 UI

#45 🐛 fix: 영화 검색 로직 잘못된 부분 수정
  src/modules/services/keywordService.ts
Labels: 🐞 버그
